default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: taskApp_development

test:
  <<: *default
  database: taskApp_test
  

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: taskApp_production
  username: taskApp
  password: <%= ENV['TASKAPP_DATABASE_PASSWORD'] %>